POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdWxpayIsImlkIjoiNjMxNzNlNGQ2YmY1OWMxOWRlYmJmODQ5IiwiaWF0IjoxNjYyNDY4MDg3LCJleHAiOjE2NjI0NzE2ODd9.56j4JfAdQqMSRjzZ9F6R5kuzDvfakKR349tKlGPLVNo

{
    "title": "delete me",
    "author": "Pauli Karels",
    "url": "http://localhost:3003/api/blogs",
    "likes": 0,
    "userId": "62fbdf9dd2e04d91e97ae42c"
}